"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['gui.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
       'plist': {
           'PyRuntimeLocations': [
            '@executable_path/../Frameworks/libpython3.6m.dylib',
            '/Users/sinabooeshaghi/software/anaconda/envs/poseidon_controller/lib/libpython3.6m.dylib'
           ]
       }}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
